/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package primetechfinal;

import primetechfinal.dao.EmpleadoDAO;
import primetechfinal.model.Empleado;
import primetechfinal.sesion.Sesion;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author dpjos
 */
public class LoginFrame extends javax.swing.JFrame {

    // logger para guardar en el archivo de log todo lo que pasa en el login
    private static final Logger logger = LogManager.getLogger(LoginFrame.class);

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblError = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("EMAIL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("CONTRASEÑA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel3.setText("PRIME TECH SYSTEMS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 200, 40));

        txtPassword.setText("jPasswordField1");
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 200, 40));
        getContentPane().add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 680, 90));

        btnIniciarSesion.setBackground(new java.awt.Color(0, 153, 255));
        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("INICIAR SESIÓN");
        btnIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 300, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        String email = txtEmail.getText().trim();
        String pass  = new String(txtPassword.getPassword());//lo hacemos por seguridad, para que no se quede guardada la contraseña en el string

        // valido los campos antes de ir a la base de datos
        if (!validarCampos(email, pass)) return;

        try {
            EmpleadoDAO dao = new EmpleadoDAO();
            Empleado emp = dao.login(email, pass);

            if (emp != null) {
                // guardo en el log quien ha entrado y cuando
                logger.info("Login correcto - empleado: {} ({})", emp.getNombreCompleto(), email);
                Sesion.iniciar(emp);
                new Pantalla().setVisible(true);
                this.dispose();//necesario, ya que si hacemos un setvisiblefalse seguiria en memoria
            } else {
                // busco el empleado para saber si el null viene de cuenta bloqueada o de contraseña incorrecta
                Empleado empConsulta = dao.buscarPorEmail(email);
                if (empConsulta != null && empConsulta.isBloqueado()) {
                    // aviso con warn porque es un intento de entrar a una cuenta bloqueada
                    logger.warn("Intento de acceso a cuenta bloqueada - email: {}", email);
                    lblError.setText("<html>Cuenta bloqueada por demasiados intentos.<br>Contacte con un administrador.</html>");
                } else {
                    // contraseña incorrecta, lo guardo como advertencia
                    logger.warn("Intento de login fallido - email: {}", email);
                    lblError.setText("Email o contraseña incorrectos.");
                }
            }
        } catch (Exception ex) {
            // si hay un error de conexion o similar lo guardo como error grave
            logger.error("Error al intentar iniciar sesion - email: {}", email, ex);
            lblError.setText("Error de conexión: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    // compruebo que los campos sean correctos antes de enviar nada a la BD
    private boolean validarCampos(String email, String pass) {

        // compruebo que no esten vacios
        if (email.isEmpty()) {
            lblError.setText("El email no puede estar vacío.");
            return false;
        }
        if (pass.isEmpty()) {
            lblError.setText("La contraseña no puede estar vacía.");
            return false;
        }

        // compruebo que el email tenga un formato valido (que tenga @ y un punto despues)
        if (!email.matches("^[^@]+@[^@]+\\.[^@]+$")) {
            lblError.setText("El formato del email no es válido.");
            return false;
        }

        // la contraseña debe tener al menos 6 caracteres
        if (pass.length() < 5) {
            lblError.setText("La contraseña debe tener al menos 5 caracteres.");
            return false;
        }

        // si llega aqui todo esta bien, limpio el error por si habia alguno antes
        lblError.setText("");
        return true;
    }

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        txtPassword.setText("");
    }//GEN-LAST:event_txtPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.error("Error al cargar el look and feel", ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblError;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
