/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package primetechfinal;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import primetechfinal.dao.ClienteDAO;
import primetechfinal.dao.ProductoDAO;
import primetechfinal.dao.VentaDAO;
import primetechfinal.model.Cliente;
import primetechfinal.model.DetalleVenta;
import primetechfinal.model.Producto;
import primetechfinal.model.Venta;
import primetechfinal.sesion.Sesion;
import primetechfinal.util.FacturaHTML;
/**
 *
 * @author dpjos
 */
public class Pantalla extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pantalla.class.getName());
    private primetechfinal.model.Producto productoActual = null; //Guarda el producto que se está editando. 
    //Si es null significa que estamos creando uno nuevo. Si tiene valor significa que estamos editando ese producto
    
    private Cliente clienteActual = null; // null = creando, con valor = editando
    private ClienteDAO clienteDAO = new ClienteDAO();
    private ProductoDAO productoDAO = new ProductoDAO();//instanciamos para no hacer new ProductoDAO cada vez que lo utilicemos
    private VentaDAO ventaDAO = new VentaDAO();
    private Venta ventaActual = null; // null = nueva venta, con valor = editando
    // listas paralelas al combobox de clientes y productos en el dialog de venta
    private java.util.List<Cliente> clientesCombo = new java.util.ArrayList<>();
    private java.util.List<Producto> productosCombo = new java.util.ArrayList<>();
    public Pantalla() {
        initComponents();
        lblEmpleado.setText(Sesion.getEmpleado().getNombreCompleto() 
                        + " · " + Sesion.getEmpleado().getCargo());//necesario para saber que empleado esta conectado
        
        cargarTablaProductos();//asi cargarmos las tablas nada mas empezar el programa
        cargarTablaClientes();
        cargarTablaVentas();
        cargarEstadisticas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogProductos = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtPrecioCompra = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        btnGuardarProducto = new javax.swing.JButton();
        btnCancelarProducto = new javax.swing.JButton();
        DialogClientes = new javax.swing.JDialog();
        cmbTipoCliente = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblDni = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        lblRazonSocial = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        lblCif = new javax.swing.JLabel();
        txtCif = new javax.swing.JTextField();
        lblContacto = new javax.swing.JLabel();
        txtContacto = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEmailCliente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDireccionCliente = new javax.swing.JTextField();
        btnGuardarCliente = new javax.swing.JButton();
        btnCancelarCliente = new javax.swing.JButton();
        DialogVenta = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cmbClienteVenta = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        cmbMetodoPago = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cmbProductoVenta = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        txtCantidadVenta = new javax.swing.JTextField();
        btnAgregarVenta = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCarrito = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnConfirmarVenta = new javax.swing.JButton();
        btnCancelarVenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtBuscarProducto = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        btnNuevoProducto = new javax.swing.JButton();
        btnEditarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblVentasHoy = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblVentasMes = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblProductoTop = new javax.swing.JLabel();
        btnNuevaVenta = new javax.swing.JButton();
        btnVerFactura = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        txtBuscarVenta = new javax.swing.JTextField();
        btnBuscarVenta = new javax.swing.JButton();
        btnEditarVenta = new javax.swing.JButton();
        btnEliminarVenta = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnNuevoCliente = new javax.swing.JButton();
        txtBuscarCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        btnEditarCliente = new javax.swing.JButton();
        btnEliminarProducto1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        lblCerrarSesion = new javax.swing.JLabel();

        DialogProductos.setMinimumSize(new java.awt.Dimension(800, 611));
        DialogProductos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Nombre:");
        DialogProductos.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Descripción:");
        DialogProductos.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Precio Compra:");
        DialogProductos.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Precio Venta:");
        DialogProductos.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Stock:");
        DialogProductos.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel7.setText("PRODUCTOS");
        DialogProductos.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));
        DialogProductos.getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 160, -1));
        DialogProductos.getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 160, -1));
        DialogProductos.getContentPane().add(txtPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 160, -1));
        DialogProductos.getContentPane().add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 160, -1));
        DialogProductos.getContentPane().add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 160, -1));

        btnGuardarProducto.setBackground(new java.awt.Color(0, 255, 51));
        btnGuardarProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuardarProducto.setText("GUARDAR");
        btnGuardarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProductoActionPerformed(evt);
            }
        });
        DialogProductos.getContentPane().add(btnGuardarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 560, -1, -1));

        btnCancelarProducto.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelarProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelarProducto.setText("CANCELAR");
        btnCancelarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProductoActionPerformed(evt);
            }
        });
        DialogProductos.getContentPane().add(btnCancelarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 560, -1, -1));

        DialogClientes.setMinimumSize(new java.awt.Dimension(900, 610));
        DialogClientes.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbTipoCliente.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        cmbTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "particular", "empresa" }));
        cmbTipoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoClienteActionPerformed(evt);
            }
        });
        DialogClientes.getContentPane().add(cmbTipoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel8.setText("CLIENTES");
        DialogClientes.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Tipo:");
        DialogClientes.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Nombre:");
        DialogClientes.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));
        DialogClientes.getContentPane().add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 150, -1));

        lblApellidos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblApellidos.setText("Apellidos:");
        DialogClientes.getContentPane().add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));
        DialogClientes.getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 150, -1));

        lblDni.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDni.setText("DNI:");
        DialogClientes.getContentPane().add(lblDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));
        DialogClientes.getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 150, -1));

        lblRazonSocial.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblRazonSocial.setText("Razón Social:");
        DialogClientes.getContentPane().add(lblRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, -1, -1));
        DialogClientes.getContentPane().add(txtRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 150, -1));

        lblCif.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCif.setText("CIF:");
        DialogClientes.getContentPane().add(lblCif, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, -1));
        DialogClientes.getContentPane().add(txtCif, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 150, -1));

        lblContacto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblContacto.setText("Contacto:");
        DialogClientes.getContentPane().add(lblContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, -1, -1));
        DialogClientes.getContentPane().add(txtContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 150, -1));

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTelefono.setText("Teléfono:");
        DialogClientes.getContentPane().add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        DialogClientes.getContentPane().add(txtTelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 150, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Email:");
        DialogClientes.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        DialogClientes.getContentPane().add(txtEmailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 160, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Dirección:");
        DialogClientes.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));
        DialogClientes.getContentPane().add(txtDireccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 160, -1));

        btnGuardarCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuardarCliente.setText("GUARDAR");
        btnGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClienteActionPerformed(evt);
            }
        });
        DialogClientes.getContentPane().add(btnGuardarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, -1, -1));

        btnCancelarCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelarCliente.setText("CANCELAR");
        btnCancelarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarClienteActionPerformed(evt);
            }
        });
        DialogClientes.getContentPane().add(btnCancelarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, -1, -1));

        DialogVenta.setMinimumSize(new java.awt.Dimension(1000, 750));
        DialogVenta.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel16.setText("VENTAS");
        DialogVenta.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setText("Cliente:");
        DialogVenta.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        cmbClienteVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmbClienteVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        DialogVenta.getContentPane().add(cmbClienteVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 180, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setText("Método de Pago:");
        DialogVenta.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        cmbMetodoPago.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmbMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "efectivo", "tarjeta", "transferencia", " " }));
        DialogVenta.getContentPane().add(cmbMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 190, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setText("Producto:");
        DialogVenta.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        cmbProductoVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DialogVenta.getContentPane().add(cmbProductoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 180, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setText("Cantidad:");
        DialogVenta.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        txtCantidadVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCantidadVenta.setText("1");
        DialogVenta.getContentPane().add(txtCantidadVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 180, -1));

        btnAgregarVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregarVenta.setText("Agregar");
        btnAgregarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarVentaActionPerformed(evt);
            }
        });
        DialogVenta.getContentPane().add(btnAgregarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 150, 50));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel21.setText("CARRITO");
        DialogVenta.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        tblCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "P. Unit", "Subtotal"
            }
        ));
        jScrollPane4.setViewportView(tblCarrito);

        DialogVenta.getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 500, 350));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel22.setText("Total:");
        DialogVenta.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel23.setText("0.00 €");
        DialogVenta.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 580, -1, -1));

        btnConfirmarVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConfirmarVenta.setText("CONFIRMAR");
        btnConfirmarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarVentaActionPerformed(evt);
            }
        });
        DialogVenta.getContentPane().add(btnConfirmarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 660, 150, 50));

        btnCancelarVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelarVenta.setText("CANCELAR");
        btnCancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVentaActionPerformed(evt);
            }
        });
        DialogVenta.getContentPane().add(btnCancelarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 660, 140, 50));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("PRIME TECH SYSTEMS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, -10, -1, 80));

        lblEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 300, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscarProducto.setToolTipText("Buscar Producto");
        jPanel1.add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 190, -1));

        btnBuscarProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscarProducto.setText("Buscar ");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 110, 40));

        btnNuevoProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNuevoProducto.setText("Nuevo");
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, 110, 40));

        btnEditarProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditarProducto.setText("Editar");
        btnEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 260, 110, 40));

        btnEliminarProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminarProducto.setText("Eliminar");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 370, 110, 40));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripción", "Precio C", "Precio V", "Stock"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 940, 420));

        panelPrincipal.addTab("Productos", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Ventas Hoy:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblVentasHoy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblVentasHoy.setText("0.00 €");
        jPanel2.add(lblVentasHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Ventas este mes:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        lblVentasMes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblVentasMes.setText("0");
        jPanel2.add(lblVentasMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Más vendido:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        lblProductoTop.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblProductoTop.setText("-");
        jPanel2.add(lblProductoTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 160, 20));

        btnNuevaVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNuevaVenta.setText("Nueva Venta");
        btnNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaVentaActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 320, 160, 40));

        btnVerFactura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVerFactura.setText("Realizar Factura");
        btnVerFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerFacturaActionPerformed(evt);
            }
        });
        jPanel2.add(btnVerFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 390, -1, 40));

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Fecha", "Total", "Método Pago"
            }
        ));
        jScrollPane3.setViewportView(tblVentas);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 820, 370));

        txtBuscarVenta.setToolTipText("Buscar Venta");
        txtBuscarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarVentaActionPerformed(evt);
            }
        });
        jPanel2.add(txtBuscarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 180, 40));

        btnBuscarVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscarVenta.setText("Buscar");
        btnBuscarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVentaActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 40, 150, 40));

        btnEditarVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditarVenta.setText("Editar");
        btnEditarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarVentaActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 190, 160, 40));

        btnEliminarVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminarVenta.setText("Eliminar");
        btnEliminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVentaActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, 160, 40));

        panelPrincipal.addTab("Ventas", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevoCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevoCliente.setText("Nuevo");
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });
        jPanel3.add(btnNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 90, 90, -1));

        txtBuscarCliente.setToolTipText("Buscar Cliente");
        jPanel3.add(txtBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 190, -1));

        btnBuscarCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarCliente.setText("Buscar ");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, 90, -1));

        btnEditarCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditarCliente.setText("Editar");
        btnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 140, 90, -1));

        btnEliminarProducto1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarProducto1.setText("Eliminar");
        btnEliminarProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProducto1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminarProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 190, 90, -1));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo", "Nombre/Razón Social", "Teléfono", "Email"
            }
        ));
        jScrollPane2.setViewportView(tblClientes);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 900, 380));

        panelPrincipal.addTab("Clientes", jPanel3);

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1080, 520));

        lblCerrarSesion.setForeground(new java.awt.Color(0, 102, 255));
        lblCerrarSesion.setText("Cerrar Sesión");
        lblCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
        });
        getContentPane().add(lblCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        try {
        DefaultTableModel m = (DefaultTableModel) tblProductos.getModel(); //necesario para interactuar con la tabla
        m.setRowCount(0);//eliminamos contenido de la tabla
        for (Producto p : productoDAO.buscarPorNombre(txtBuscarProducto.getText())) {//como devuelve un arraylist el metodo
            //buscar por nombre lo introducimos en el foreach
            m.addRow(new Object[]{
                p.getIdProducto(), p.getNombre(), p.getDescripcion(),
                p.getPrecioCompra(), p.getPrecioVenta(), p.getStock()
            });
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoActionPerformed
        // ponemos null para indicar que estamos creando un producto nuevo
        productoActual = null;
        limpiarCamposProducto();
        DialogProductos.setVisible(true);
    }//GEN-LAST:event_btnNuevoProductoActionPerformed

    private void btnGuardarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProductoActionPerformed
        try {
        Producto p = productoActual != null ? productoActual : new Producto();//operador ternario, si editamos usamos el producto actual
        //si no utilizamos uno nuevo
        p.setNombre(txtNombre.getText());
        p.setDescripcion(txtDescripcion.getText());
        p.setPrecioCompra(Double.parseDouble(txtPrecioCompra.getText()));
        p.setPrecioVenta(Double.parseDouble(txtPrecioVenta.getText()));
        p.setStock(Integer.parseInt(txtStock.getText()));
        if (productoActual != null) productoDAO.actualizar(p);
        else                        productoDAO.insertar(p);
        DialogProductos.setVisible(false);
        cargarTablaProductos();
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Revisa los campos numéricos.");
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnGuardarProductoActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        int fila = tblProductos.getSelectedRow();//obtenemos fila seleccionada
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un producto.");//si no hay nada seleccionado
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "¿Eliminar producto?");//confirmacion para eliminar producto
        if (confirm != JOptionPane.YES_OPTION) return;
        try {
            productoDAO.eliminar((int) tblProductos.getValueAt(fila, 0));//le pasamos el id, y el metodo.eliminar ya sabe eliminar toda la fila
            cargarTablaProductos();//actualizamos tabla
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProductoActionPerformed
        int fila = tblProductos.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un producto.");
            return;
        }
        productoActual = new Producto();
        productoActual.setIdProducto((int) tblProductos.getValueAt(fila, 0));
        limpiarCamposProducto();
        txtNombre.setText((String) tblProductos.getValueAt(fila, 1));
        txtDescripcion.setText((String) tblProductos.getValueAt(fila, 2));
        txtPrecioCompra.setText(String.valueOf(tblProductos.getValueAt(fila, 3)));
        txtPrecioVenta.setText(String.valueOf(tblProductos.getValueAt(fila, 4)));
        txtStock.setText(String.valueOf(tblProductos.getValueAt(fila, 5)));
        DialogProductos.setVisible(true);
    }//GEN-LAST:event_btnEditarProductoActionPerformed

    private void btnCancelarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProductoActionPerformed
        DialogProductos.setVisible(false);
    }//GEN-LAST:event_btnCancelarProductoActionPerformed

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        clienteActual = null;
        limpiarCamposCliente();
        cmbTipoCliente.setSelectedIndex(0); // selecciona particular por defecto
        actualizarVisibilidadCampos();
        DialogClientes.setVisible(true);
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        try {
        DefaultTableModel m = (DefaultTableModel) tblClientes.getModel();
        m.setRowCount(0);
        for (Cliente c : clienteDAO.buscarPorNombre(txtBuscarCliente.getText())) {
            m.addRow(new Object[]{
                c.getIdCliente(), c.getTipo(),
                c.getNombreVisible(), c.getTelefono(), c.getEmail()
            });
        }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
        int fila = tblClientes.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un cliente.");
            return;
        }
        clienteActual = new Cliente();
        clienteActual.setIdCliente((int) tblClientes.getValueAt(fila, 0));
        clienteActual.setTipo((String) tblClientes.getValueAt(fila, 1));
        limpiarCamposCliente();
        // cargamos tipo en el combobox
        cmbTipoCliente.setSelectedItem(clienteActual.getTipo());
        actualizarVisibilidadCampos();
        // cargamos nombre visible en el campo correspondiente
        if (clienteActual.getTipo().equals("particular")) {
            // separamos nombre y apellidos del nombre visible (columna 2)
            txtNombreCliente.setText((String) tblClientes.getValueAt(fila, 2));
        } else {
            txtRazonSocial.setText((String) tblClientes.getValueAt(fila, 2));
        }
        txtTelefonoCliente.setText((String) tblClientes.getValueAt(fila, 3));
        txtEmailCliente.setText((String) tblClientes.getValueAt(fila, 4));
        DialogClientes.setVisible(true);
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    private void btnEliminarProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProducto1ActionPerformed
        int fila = tblClientes.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un cliente.");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "¿Eliminar cliente?");
        if (confirm != JOptionPane.YES_OPTION) return;
        try {
            clienteDAO.eliminar((int) tblClientes.getValueAt(fila, 0));
            cargarTablaClientes();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarProducto1ActionPerformed

    private void btnGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClienteActionPerformed
        try {
        Cliente c = clienteActual != null ? clienteActual : new Cliente();
        c.setTelefono(txtTelefonoCliente.getText());
        c.setEmail(txtEmailCliente.getText());
        c.setDireccion(txtDireccionCliente.getText());
        boolean esParticular = cmbTipoCliente.getSelectedItem().equals("particular");
        if (esParticular) {
            c.setNombre(txtNombreCliente.getText());
            c.setApellidos(txtApellidos.getText());
            c.setDni(txtDni.getText());
            if (clienteActual != null) clienteDAO.actualizarParticular(c);
            else                       clienteDAO.insertarParticular(c);
        } else {
            c.setRazonSocial(txtRazonSocial.getText());
            c.setCif(txtCif.getText());
            c.setContactoNombre(txtContacto.getText());
            if (clienteActual != null) clienteDAO.actualizarEmpresa(c);
            else                       clienteDAO.insertarEmpresa(c);
        }
        DialogClientes.setVisible(false);
        cargarTablaClientes();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnGuardarClienteActionPerformed

    private void cmbTipoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoClienteActionPerformed
         actualizarVisibilidadCampos();
    }//GEN-LAST:event_cmbTipoClienteActionPerformed

    private void btnCancelarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarClienteActionPerformed
        DialogClientes.setVisible(false);
    }//GEN-LAST:event_btnCancelarClienteActionPerformed

    private void btnAgregarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarVentaActionPerformed
        int idxProducto = cmbProductoVenta.getSelectedIndex();
        if (idxProducto < 0 || idxProducto >= productosCombo.size()) return;
        try {
            int cantidad = Integer.parseInt(txtCantidadVenta.getText());
            if (cantidad <= 0) { JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor que 0."); return; }
            // obtenemos el producto directamente por índice, sin buscar por nombre
            Producto p = productosCombo.get(idxProducto);
            double subtotal = cantidad * p.getPrecioVenta();
            DefaultTableModel m = (DefaultTableModel) tblCarrito.getModel();
            m.addRow(new Object[]{p.getNombre(), cantidad, p.getPrecioVenta(), subtotal});
            recalcularTotal();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser un número.");
        }
    }//GEN-LAST:event_btnAgregarVentaActionPerformed

    private void btnNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaVentaActionPerformed
        ventaActual = null; // indicamos que es venta nueva
        limpiarDialogVenta();
        DialogVenta.setVisible(true);
    }//GEN-LAST:event_btnNuevaVentaActionPerformed

    private void btnVerFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerFacturaActionPerformed
        int fila = tblVentas.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona una venta.");
            return;
        }
        try {
            int id = (int) tblVentas.getValueAt(fila, 0);
            Venta v = ventaDAO.cargarVentaCompleta(id);
            FacturaHTML.generarYAbrir(v, "PRIME TECH SYSTEMS");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnVerFacturaActionPerformed

    private void btnConfirmarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarVentaActionPerformed
        DefaultTableModel m = (DefaultTableModel) tblCarrito.getModel();
        if (m.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Añade productos al carrito.");
            return;
        }
        try {
            Venta v = ventaActual != null ? ventaActual : new Venta();
            // cliente: usamos clientesCombo por índice (índice 0 = Sin cliente)
            int idxCliente = cmbClienteVenta.getSelectedIndex();
            if (idxCliente > 0 && idxCliente - 1 < clientesCombo.size()) {
                v.setIdCliente(clientesCombo.get(idxCliente - 1).getIdCliente());
            } else {
                v.setIdCliente(0); // sin cliente
            }
            v.setIdEmpleado(Sesion.getEmpleado().getIdEmpleado());
            v.setMetodoPago(cmbMetodoPago.getSelectedItem().toString());
            // reconstruimos los detalles desde el carrito
            v.getDetalles().clear();
            for (int i = 0; i < m.getRowCount(); i++) {
                String nombre = (String) m.getValueAt(i, 0);
                int cantidad  = (int)    m.getValueAt(i, 1);
                double precio = (double) m.getValueAt(i, 2);
                // buscamos el producto por nombre exacto (guardamos getNombre() en el carrito)
                List<Producto> lista = productoDAO.buscarPorNombre(nombre);
                if (!lista.isEmpty()) {
                    v.getDetalles().add(new DetalleVenta(lista.get(0).getIdProducto(), nombre, cantidad, precio));
                }
            }
            if (ventaActual != null) ventaDAO.actualizar(v);//decidimos si actualiza o inserta
            else                     ventaDAO.registrarVenta(v);
            DialogVenta.setVisible(false);
            cargarTablaVentas();
            cargarEstadisticas();
            JOptionPane.showMessageDialog(this, ventaActual != null ? "Venta actualizada correctamente." : "Venta registrada correctamente.");//operacion ternaria ahorramos espacio, mejor que hacer if else
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnConfirmarVentaActionPerformed

    private void btnCancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVentaActionPerformed
        DialogVenta.setVisible(false);
    }//GEN-LAST:event_btnCancelarVentaActionPerformed

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        int confirm = JOptionPane.showConfirmDialog(this, "¿Cerrar sesión?");
        if (confirm != JOptionPane.YES_OPTION) return;//mostramos una confirmación
        Sesion.cerrar();
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCerrarSesionMouseClicked

    private void txtBuscarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarVentaActionPerformed

    private void btnBuscarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVentaActionPerformed
        try {
            DefaultTableModel m = (DefaultTableModel) tblVentas.getModel();
            m.setRowCount(0);
            for (Venta v : ventaDAO.buscarPorCliente(txtBuscarVenta.getText())) {
                m.addRow(new Object[]{
                    v.getIdVenta(), v.getNombreCliente(),
                    v.getFechaVenta(), v.getTotal(), v.getMetodoPago()
                });
            }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarVentaActionPerformed

    private void btnEliminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVentaActionPerformed
        int fila = tblVentas.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona una venta.");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "¿Eliminar la venta seleccionada?");
        if (confirm != JOptionPane.YES_OPTION) return;
        try {
            ventaDAO.eliminar((int) tblVentas.getValueAt(fila, 0));
            cargarTablaVentas();
            cargarEstadisticas();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarVentaActionPerformed

    private void btnEditarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarVentaActionPerformed
        int fila = tblVentas.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona una venta.");
            return;
        }
        try {
            int id = (int) tblVentas.getValueAt(fila, 0);
            ventaActual = ventaDAO.cargarVentaCompleta(id);
            if (ventaActual == null) return;//si no hay venta volvemos, quizas es redundante, pero por si acaso
            // preparamos el dialog con los datos actuales
            limpiarDialogVenta();
            // seleccionamos el cliente en el combobox buscando por ID en clientesCombo
            if (ventaActual.getIdCliente() > 0) {
                for (int i = 0; i < clientesCombo.size(); i++) {
                    if (clientesCombo.get(i).getIdCliente() == ventaActual.getIdCliente()) {
                        cmbClienteVenta.setSelectedIndex(i + 1); // +1 porque índice 0 es "Sin cliente"
                        break;
                    }
                }
            }
            // método de pago
            cmbMetodoPago.setSelectedItem(ventaActual.getMetodoPago());
            // cargamos los productos del carrito
            DefaultTableModel m = (DefaultTableModel) tblCarrito.getModel();
            m.setRowCount(0);
            for (DetalleVenta d : ventaActual.getDetalles()) {
                m.addRow(new Object[]{
                    d.getNombreProducto(), d.getCantidad(),
                    d.getPrecioUnitario(), d.getCantidad() * d.getPrecioUnitario()
                });
            }
            recalcularTotal();
            DialogVenta.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnEditarVentaActionPerformed

    private void cargarTablaProductos() {
    try {
        DefaultTableModel m = (DefaultTableModel) tblProductos.getModel();
        m.setRowCount(0);
        for (Producto p : productoDAO.listarTodos()) {
            m.addRow(new Object[]{
                p.getIdProducto(), p.getNombre(), p.getDescripcion(),
                p.getPrecioCompra(), p.getPrecioVenta(), p.getStock()
            });
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }
    private void cargarTablaClientes() {
    try {
        DefaultTableModel m = (DefaultTableModel) tblClientes.getModel();
        m.setRowCount(0);
        for (Cliente c : clienteDAO.listarTodos()) {
            m.addRow(new Object[]{
                c.getIdCliente(), c.getTipo(),
                c.getNombreVisible(), c.getTelefono(), c.getEmail()
            });
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
     }
    }
    private void cargarTablaVentas() {
    try {
        DefaultTableModel m = (DefaultTableModel) tblVentas.getModel();
        m.setRowCount(0);
        for (Venta v : ventaDAO.listarTodas()) {
            m.addRow(new Object[]{
                v.getIdVenta(), v.getNombreCliente(),
                v.getFechaVenta(), v.getTotal(), v.getMetodoPago()
            });
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }
    private void cargarEstadisticas() {
    try {
        lblVentasHoy.setText(String.format("%.2f €", ventaDAO.totalVentasHoy()));
        lblVentasMes.setText(String.valueOf(ventaDAO.ventasMes()));
        lblProductoTop.setText(ventaDAO.productoMasVendido());
    } catch (SQLException ex) {
        lblVentasHoy.setText("Error");
        }
    }
    private void limpiarCamposProducto() {
    txtNombre.setText("");
    txtDescripcion.setText("");
    txtPrecioCompra.setText("");//ASI NO REPETIMOS CODIGO
    txtPrecioVenta.setText("");
    txtStock.setText("");
    }
    private void limpiarCamposCliente() {
    txtNombreCliente.setText("");
    txtApellidos.setText("");
    txtDni.setText("");
    txtRazonSocial.setText("");
    txtCif.setText("");
    txtContacto.setText("");
    txtTelefonoCliente.setText("");
    txtEmailCliente.setText("");
    txtDireccionCliente.setText("");
    }
    private void actualizarVisibilidadCampos() {
    boolean esParticular = cmbTipoCliente.getSelectedItem().equals("particular");
    lblApellidos.setVisible(esParticular);
    txtApellidos.setVisible(esParticular);
    lblDni.setVisible(esParticular);
    txtDni.setVisible(esParticular);
    lblRazonSocial.setVisible(!esParticular);//muestra o los campos de particulares o los de empresa según el combobox
    txtRazonSocial.setVisible(!esParticular);
    lblCif.setVisible(!esParticular);
    txtCif.setVisible(!esParticular);
    lblContacto.setVisible(!esParticular);
    txtContacto.setVisible(!esParticular);
    }
    private void limpiarDialogVenta() {
    try {
        // cargamos clientes en el combobox y en la lista paralela (índice 0 = Sin cliente)
        clientesCombo.clear();
        cmbClienteVenta.removeAllItems();
        cmbClienteVenta.addItem("Sin cliente");
        for (Cliente c : clienteDAO.listarTodos()) {
            clientesCombo.add(c);
            cmbClienteVenta.addItem(c.getNombreVisible()); // nombre legible, no toString()
        }
        // cargamos productos en el combobox y en la lista paralela
        productosCombo.clear();
        cmbProductoVenta.removeAllItems();
        for (Producto p : productoDAO.listarTodos()) {
            productosCombo.add(p);
            cmbProductoVenta.addItem(p.getNombre()); // nombre legible, no toString()
        }
        // limpiamos carrito
        ((DefaultTableModel) tblCarrito.getModel()).setRowCount(0);
        jLabel23.setText("0.00 €");
        txtCantidadVenta.setText("1");
        cmbMetodoPago.setSelectedIndex(0);
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }
    private void recalcularTotal() {
    // suma todos los subtotales del carrito y actualiza el label
    DefaultTableModel m = (DefaultTableModel) tblCarrito.getModel();
    double total = 0;
    for (int i = 0; i < m.getRowCount(); i++) {
        total += (double) m.getValueAt(i, 3);
    }
    jLabel23.setText(String.format("%.2f €", total));
    }
     
   
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> new Pantalla().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DialogClientes;
    private javax.swing.JDialog DialogProductos;
    private javax.swing.JDialog DialogVenta;
    private javax.swing.JButton btnAgregarVenta;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnBuscarVenta;
    private javax.swing.JButton btnCancelarCliente;
    private javax.swing.JButton btnCancelarProducto;
    private javax.swing.JButton btnCancelarVenta;
    private javax.swing.JButton btnConfirmarVenta;
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnEditarProducto;
    private javax.swing.JButton btnEditarVenta;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnEliminarProducto1;
    private javax.swing.JButton btnEliminarVenta;
    private javax.swing.JButton btnGuardarCliente;
    private javax.swing.JButton btnGuardarProducto;
    private javax.swing.JButton btnNuevaVenta;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JButton btnVerFactura;
    private javax.swing.JComboBox<String> cmbClienteVenta;
    private javax.swing.JComboBox<String> cmbMetodoPago;
    private javax.swing.JComboBox<String> cmbProductoVenta;
    private javax.swing.JComboBox<String> cmbTipoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblCif;
    private javax.swing.JLabel lblContacto;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblProductoTop;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblVentasHoy;
    private javax.swing.JLabel lblVentasMes;
    private javax.swing.JTabbedPane panelPrincipal;
    private javax.swing.JTable tblCarrito;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBuscarCliente;
    private javax.swing.JTextField txtBuscarProducto;
    private javax.swing.JTextField txtBuscarVenta;
    private javax.swing.JTextField txtCantidadVenta;
    private javax.swing.JTextField txtCif;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
